### ISSUE TITLE
Empty message pushed to synqueue to stop server needs looking at

### ISSUE THREAD

**Issue by TimDykes** [ugovaretto/zrf#21]
Commit efd6058 replaced the ByteArray() with ReqRep() to allow compilation, this should be reconsidered - no port or id is given, so on send this will probably cause a problem. 

Fix is likely to replace ReqRep() with properly filled structure, i.e. correct port ID and empty message - what about request ID?

**Comment by ugovaretto** [comment]
As a reminder :-) 

Close it after you make the following changes:
- Push tuple instead of ByteArray
- PushFront instead of Push in Stop
- Check req id: if zero do not put response in queue

I'll wait for your push before I perform another couple of harmless (to you) changes and extract SyncQueue and Serialize, this is  required before we start working on JPEG compression with the tjpp library.
